### ISSUE TITLE
Also add multi-platform support

### ISSUE THREAD

**Issue by obi-wan-shinobi** [remla25-team15/app-frontend#6]
The base image doesn't have support for darwin and windows but we can still build images that support 
 linux/amd64,linux/arm64.

We'll have to update the workflow's docker/build-push-action:

```yaml
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMG }}:${{ env.version }}
            ${{ env.IMG }}:${{ env.version_major }}.${{ env.version_minor }}.latest
            ${{ env.IMG }}:${{ env.version_major }}.latest
            ${{ env.IMG }}:latest
```
